import React, { useCallback, useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import API from '../../utils/api';

const STATUSES = ['pending_approval','approved','scheduled','sent','failed','cancelled','converted','rejected'];
const label = value => String(value || '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
const money = value => `Rs. ${Number(value || 0).toLocaleString()}`;

export default function Marketing() {
  const [dashboard,setDashboard]=useState(null); const [items,setItems]=useState([]); const [settings,setSettings]=useState(null);
  const [behavior,setBehavior]=useState(null);
  const [segments,setSegments]=useState(null); const [analyzing,setAnalyzing]=useState(false);
  const [loading,setLoading]=useState(true); const [status,setStatus]=useState(''); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [selected,setSelected]=useState(null);
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const [d,r,s,b,g]=await Promise.all([API.get('/admin/marketing/dashboard'),API.get('/admin/marketing/recommendations',{params:{status,page}}),API.get('/admin/marketing/settings'),API.get('/admin/marketing/behavior'),API.get('/admin/marketing/segments')]);setDashboard(d.data);setItems(r.data.items);setPages(r.data.pages||1);setSettings(s.data);setBehavior(b.data);setSegments(g.data);}catch(e){if(!silent)toast.error(e.response?.data?.message||'Marketing data could not be loaded');}finally{if(!silent)setLoading(false);}},[status,page]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const timer=setInterval(()=>load(true),30000);return()=>clearInterval(timer);},[load]);
  const action=async(id,name,body={})=>{if(!window.confirm(`${label(name)} this recommendation?`))return;try{await API.post(`/admin/marketing/recommendations/${id}/${name}`,body);toast.success('Recommendation updated');setSelected(null);load();}catch(e){toast.error(e.response?.data?.message||'Action failed');}};
  const saveSettings=async()=>{try{const {data}=await API.put('/admin/marketing/settings',settings);setSettings(data);toast.success('Marketing settings saved');}catch(e){toast.error(e.response?.data?.message||'Settings could not be saved');}};
  const saveEdit=async()=>{try{await API.put(`/admin/marketing/recommendations/${selected._id}`,selected);toast.success('Email saved');setSelected(null);load();}catch(e){toast.error(e.response?.data?.message||'Save failed');}};
  const analyzeNow=async()=>{setAnalyzing(true);try{const {data}=await API.post('/admin/marketing/analyze');toast.success(`Analysis complete: ${data.created||0} campaign recommendation(s) created`);await load();}catch(e){toast.error(e.response?.data?.message||'Analysis failed');}finally{setAnalyzing(false);}};
  if(loading&&!dashboard)return <div className="p-12 text-center text-gray-400">Loading marketing dashboard…</div>;
  const cards=[['Suggested',(dashboard?.stats?.suggested||0)],['Pending approval',dashboard?.stats?.pending_approval||0],['Approved',dashboard?.stats?.approved||0],['Scheduled',dashboard?.stats?.scheduled||0],['Sent',dashboard?.stats?.sent||0],['Failed',dashboard?.stats?.failed||0],['Cancelled',dashboard?.stats?.cancelled||0],['Converted',dashboard?.stats?.converted||0],['Revenue',money(dashboard?.revenue)],['Conversion rate',`${Number(dashboard?.conversionRate||0).toFixed(1)}%`],['Unsubscribes',dashboard?.unsubscribes||0],['Auto approval',dashboard?.autoApprovalEnabled?'On':'Off']];
  return <div className="space-y-6 pb-12">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="font-display text-2xl font-bold text-gray-900">Marketing</h1><p className="text-sm text-gray-500">Live, consent-aware behavior analysis and AI-assisted retargeting</p></div><div className="flex gap-2"><button className="btn-outline" disabled={analyzing} onClick={analyzeNow}>{analyzing?'Analyzing…':'Analyze & create campaigns'}</button><button className="btn-primary" onClick={()=>load()}>Refresh</button></div></div>
    {!settings?.enabled&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><strong>Safe rollout:</strong> Retargeting is disabled. Enable tracking first, then recommendation generation, and keep automatic sending off until recommendations have been reviewed.</div>}
    {settings&&!settings.trackingEnabled&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><strong>Customer behavior tracking is off.</strong> Enable “Enable event tracking” below and save the settings. Only signed-in customers who have given marketing consent are tracked.</div>}
    <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{cards.map(([k,v])=><div key={k} className="bg-white rounded-2xl border border-gray-100 p-4"><p className="text-xs text-gray-500">{k}</p><p className="text-xl font-bold text-gray-900 mt-1">{v}</p></div>)}</div>
    <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
      <div className="p-5 border-b"><h2 className="font-bold text-gray-900">Customer behavior</h2><p className="text-xs text-gray-500 mt-1">Storefront activity captured from signed-in customers with marketing consent.</p></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 p-5">
        {[['Total events',behavior?.totalEvents||0],['Last 24 hours',behavior?.eventsLast24Hours||0],['Tracked customers',behavior?.trackedCustomers||0],['Consented customers',behavior?.consentedCustomers||0]].map(([key,value])=><div key={key} className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">{key}</p><p className="text-xl font-bold mt-1">{value}</p></div>)}
      </div>
      {behavior?.byType&&Object.keys(behavior.byType).length>0&&<div className="flex flex-wrap gap-2 px-5 pb-5">{Object.entries(behavior.byType).map(([type,count])=><span key={type} className="px-2.5 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-medium">{label(type)}: {count}</span>)}</div>}
      {!behavior?.recentEvents?.length?<div className="px-5 pb-6 text-sm text-gray-400">No behavior events have been captured yet. Check tracking is enabled, then test with a signed-in, newsletter-subscribed customer.</div>:<div className="overflow-x-auto border-t"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr>{['Customer','Behavior','Product','Device','Time'].map(head=><th className="p-3" key={head}>{head}</th>)}</tr></thead><tbody>{behavior.recentEvents.map(event=><tr key={event._id} className="border-t"><td className="p-3"><p className="font-medium">{event.customerId?.firstName} {event.customerId?.lastName}</p><p className="text-xs text-gray-400">{event.customerId?.email}</p></td><td className="p-3">{label(event.eventType)}</td><td className="p-3">{event.productId?.name||'—'}</td><td className="p-3">{label(event.deviceType)}</td><td className="p-3 whitespace-nowrap">{new Date(event.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
      <div className="p-5 border-b flex items-center justify-between"><div><h2 className="font-bold text-gray-900">Live customer intent segments</h2><p className="text-xs text-gray-500 mt-1">Deterministic 30-day segments; refreshes every 30 seconds. Purchasers are kept separate from abandonment audiences.</p></div><span className="text-xs text-gray-400">{segments?.generatedAt?`Updated ${new Date(segments.generatedAt).toLocaleTimeString()}`:''}</span></div>
      <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3 p-5">{Object.entries(segments?.counts||{}).map(([key,value])=><div key={key} className="rounded-xl bg-violet-50 p-3"><p className="text-xs text-violet-600">{label(key)}</p><p className="text-xl font-bold mt-1">{value}</p></div>)}</div>
      {!!segments?.items?.length&&<div className="overflow-x-auto border-t max-h-96"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500 sticky top-0"><tr>{['Customer','Segment','Views','Searches','Cart','Checkout','Purchases','Last activity'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{segments.items.slice(0,100).map(item=><tr key={item.customerId} className="border-t"><td className="p-3"><p className="font-medium">{item.customerName||'Customer'}</p><p className="text-xs text-gray-400">{item.email?.replace(/^(.{2}).*(@.*)$/,'$1••••$2')}</p></td><td className="p-3"><span className="px-2 py-1 rounded-full bg-violet-50 text-violet-700 text-xs">{label(item.segment)}</span></td><td className="p-3">{item.productViews}</td><td className="p-3">{item.searches}</td><td className="p-3">{item.cartAdds}</td><td className="p-3">{item.checkoutStarts}</td><td className="p-3">{item.purchases}</td><td className="p-3 whitespace-nowrap">{new Date(item.lastSeenAt).toLocaleString()}</td></tr>)}</tbody></table></div>}
    </section>
    {settings&&<section className="bg-white rounded-2xl border border-gray-100 p-5 space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-bold text-gray-900">Safety and frequency settings</h2><p className="text-xs text-gray-500">All automation defaults to off.</p></div><button className="btn-primary" onClick={saveSettings}>Save settings</button></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
      {[['enabled','Enable recommendations'],['trackingEnabled','Enable event tracking'],['aiEnabled','Enable AI copy analysis'],['autoApprovalEnabled','Auto approve eligible'],['automaticSendingEnabled','Enable email sending']].map(([key,text])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>{text}</label>)}
      {[['waitingPeriodDays','Wait days'],['minimumInterestScore','Minimum score'],['maximumEmailsPerWeek','Max/customer/week'],['maximumEmailsPerMonth','Max/customer/month'],['sameProductCooldownDays','Product cooldown days'],['minimumAutoApprovalConfidence','Auto approval confidence']].map(([key,text])=><label key={key} className="text-xs text-gray-500">{text}<input className="form-input mt-1" type="number" step={key.includes('Confidence')?'0.01':'1'} value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}
    </div></section>}
    <section className="bg-white rounded-2xl border border-gray-100 overflow-hidden"><div className="p-4 border-b flex items-center gap-3"><h2 className="font-bold flex-1">Email recommendations</h2><select className="form-input max-w-xs" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{STATUSES.map(s=><option value={s} key={s}>{label(s)}</option>)}</select></div>
      {items.length===0?<div className="p-12 text-center text-gray-400">No recommendations match this filter.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-gray-50 text-left text-xs text-gray-500"><tr>{['Customer','Product','Price / stock','Score','Reason','Subject','Status','Actions'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{items.map(r=><tr key={r._id} className="border-t align-top"><td className="p-3"><p className="font-medium">{r.customerId?.firstName} {r.customerId?.lastName}</p><p className="text-xs text-gray-400">{r.customerEmail?.replace(/^(.{2}).*(@.*)$/,'$1••••$2')}</p></td><td className="p-3"><div className="flex gap-2"><img className="w-12 h-12 rounded-lg object-contain bg-gray-50" src={r.productId?.thumbnail||r.productId?.images?.[0]} alt=""/><div><p className="font-medium max-w-xs">{r.productId?.name||r.productSnapshot?.name}</p><a className="text-xs text-primary" href={`/product/${r.productId?.slug||r.productSnapshot?.slug}`} target="_blank" rel="noreferrer">View product</a></div></div></td><td className="p-3 whitespace-nowrap">{money(r.productId?.isOnSale?r.productId?.salePrice:r.productId?.price)}<p className={r.productId?.stock>0?'text-green-600 text-xs':'text-red-600 text-xs'}>{r.productId?.stock>0?`${r.productId.stock} in stock`:'Out of stock'}</p></td><td className="p-3 font-bold">{r.interestScore}<p className="text-xs text-gray-400">{Math.round((r.confidence||0)*100)}%</p></td><td className="p-3 max-w-xs text-xs text-gray-600">{r.recommendationReason}</td><td className="p-3 max-w-xs">{r.subject}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-gray-100 text-xs">{label(r.status)}</span></td><td className="p-3"><div className="flex flex-wrap gap-1"><button className="text-xs text-primary" onClick={()=>setSelected(r)}>Preview/Edit</button>{r.status==='pending_approval'&&<><button className="text-xs text-green-600" onClick={()=>action(r._id,'approve')}>Approve</button><button className="text-xs text-red-600" onClick={()=>action(r._id,'reject')}>Reject</button></>}{['approved','scheduled'].includes(r.status)&&<button className="text-xs text-green-600" onClick={()=>action(r._id,'send')}>Send now</button>}{!['sent','converted','cancelled','rejected'].includes(r.status)&&<button className="text-xs text-gray-500" onClick={()=>action(r._id,'cancel')}>Cancel</button>}</div></td></tr>)}</tbody></table></div>}
      <div className="p-4 border-t flex justify-end gap-2"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span className="text-sm">{page} / {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div>
    </section>
    {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto p-6 space-y-4"><div className="flex justify-between"><h2 className="font-bold text-xl">Safe email editor</h2><button onClick={()=>setSelected(null)}>✕</button></div>{[['subject','Subject'],['previewText','Preview text'],['headline','Headline'],['ctaText','CTA text']].map(([k,l])=><label className="block text-sm" key={k}>{l}<input className="form-input mt-1" value={selected[k]||''} onChange={e=>setSelected({...selected,[k]:e.target.value})}/></label>)}<label className="block text-sm">Body<textarea rows="7" className="form-input mt-1" value={selected.emailBody||''} onChange={e=>setSelected({...selected,emailBody:e.target.value})}/></label><div className="rounded-xl bg-gray-50 p-5"><p className="text-xs text-gray-400">Preview</p><h3 className="text-xl font-bold mt-2">{selected.headline}</h3><p className="mt-2 whitespace-pre-wrap">{selected.emailBody}</p><button className="btn-primary mt-4">{selected.ctaText}</button></div><div className="flex justify-end gap-2"><button onClick={()=>setSelected(null)}>Cancel</button><button className="btn-primary" onClick={saveEdit}>Save changes</button></div></div></div>}
  </div>;
}
